SUPABASE_URL = "https://sbbdcmakyipijmrkvbfc.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiYmRjbWFreWlwaWptcmt2YmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NzEyNTEsImV4cCI6MjA1NTM0NzI1MX0.v_8r0LyV6H4rk4UFWfpZuvBbtdjJorAeoDvCxgRf1Oc"
GEMINI_API_KEY = "AIzaSyBdYwfWWf0wVP7j0ui2hsWYWTMqb-qoFUU"
GROQ_API_KEY = "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"
